name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "::set-output name=sha::$SHA"

      - name: build docker image
        run: docker build -t luckmenez/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .

      - name: push docker image registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: push docker image
        run: |
          docker push luckmenez/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
